"""changed datetime to date

Revision ID: 359206a7d0a1
Revises: f96fc70cc514
Create Date: 2023-09-01 13:21:12.069820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359206a7d0a1'
down_revision = 'f96fc70cc514'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consignment',
    sa.Column('guid', sa.String(), nullable=False),
    sa.Column('reverse_charge', sa.Boolean(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=128), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('state_code', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('destination', sa.String(length=128), nullable=True),
    sa.Column('rfq_item_no', sa.String(length=128), nullable=True),
    sa.Column('rfq_item_name', sa.String(length=128), nullable=True),
    sa.Column('goods_name', sa.String(length=128), nullable=True),
    sa.Column('hsn_no', sa.String(length=128), nullable=True),
    sa.Column('eway_no', sa.String(length=128), nullable=True),
    sa.Column('po_no', sa.String(length=128), nullable=True),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('place_of_supply', sa.String(length=128), nullable=True),
    sa.Column('lr_no', sa.String(length=128), nullable=True),
    sa.Column('lr_date', sa.Date(), nullable=True),
    sa.Column('transporter_name', sa.String(length=128), nullable=True),
    sa.Column('preparation_date', sa.Date(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('bank_detail_guid', sa.String(), nullable=True),
    sa.Column('client_guid', sa.String(), nullable=True),
    sa.Column('stockdetail_guid', sa.String(), nullable=True),
    sa.Column('stockbatchinfo_guid', sa.String(), nullable=True),
    sa.Column('itemdetail_guid', sa.String(), nullable=True),
    sa.Column('tnc_guid', sa.String(), nullable=True),
    sa.Column('signatory_guid', sa.String(), nullable=True),
    sa.Column('taxation_guid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bank_detail_guid'], ['bankdetail.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_guid'], ['client.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['itemdetail_guid'], ['itemdetail.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signatory_guid'], ['signatory.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stockbatchinfo_guid'], ['stockbatchinfo.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stockdetail_guid'], ['stockdetail.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taxation_guid'], ['taxation.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tnc_guid'], ['termsandconditions.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_consignment_guid'), 'consignment', ['guid'], unique=False)
    op.create_foreign_key(None, 'consignment_item_association', 'consignment', ['consignment_guid'], ['guid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consignment_item_association', type_='foreignkey')
    op.drop_index(op.f('ix_consignment_guid'), table_name='consignment')
    op.drop_table('consignment')
    # ### end Alembic commands ###
