"""Testing Date Fields 3

Revision ID: a02d43f25d24
Revises: a13b33125509
Create Date: 2023-08-21 12:54:57.219420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02d43f25d24'
down_revision = 'a13b33125509'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
