"""Testing Date Fields 2

Revision ID: a13b33125509
Revises: db6655b87168
Create Date: 2023-08-21 12:45:17.383092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13b33125509'
down_revision = 'db6655b87168'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
