"""Testing Date Fields

Revision ID: db6655b87168
Revises: ebd35d94dfc2
Create Date: 2023-08-21 12:38:53.173916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6655b87168'
down_revision = 'ebd35d94dfc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
