"""added Item model, made item many to many with consignment, item has a foreign key to product 

Revision ID: ebd35d94dfc2
Revises: 5254162e106f
Create Date: 2023-08-14 14:04:54.437470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd35d94dfc2'
down_revision = '5254162e106f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consignment_product_association')
    op.add_column('item', sa.Column('product_guid', sa.String(), nullable=True))
    op.create_foreign_key(None, 'item', 'product', ['product_guid'], ['guid'], ondelete='CASCADE')
    op.drop_column('product', 'purchase_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'product_guid')
    op.create_table('consignment_product_association',
    sa.Column('consignment_guid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product_guid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['consignment_guid'], ['consignment.guid'], name='consignment_product_association_consignment_guid_fkey'),
    sa.ForeignKeyConstraint(['product_guid'], ['product.guid'], name='consignment_product_association_product_guid_fkey')
    )
    # ### end Alembic commands ###
