"""Testing Date Fields 4

Revision ID: f96fc70cc514
Revises: a02d43f25d24
Create Date: 2023-08-21 13:04:02.154294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96fc70cc514'
down_revision = 'a02d43f25d24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
